# 通过外部的配置文件来配置当前的项目，支持定制化的配置
# Spring Cloud Config Server provides an HTTP resource-based API for external configuration
# https://github.com/spring-cloud-samples/config-repo/blob/main/application.yml
#
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/project/config-repo
        repos:
          development:
            pattern:
              - '*/development'
              - '*/staging'
            uri: https://github.com/development/config-repo
          staging:
            pattern:
              - '*/qa'
              - '*/production'
            uri: https://github.com/staging/config-repo